name: hunt_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.5
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  firebase_storage: ^10.2.4
  flutter_facebook_auth: ^4.0.1
  geolocator: ^8.0.1
  google_maps_flutter: ^2.0.6
  google_maps_cluster_manager: ^3.0.0+1
  font_awesome_flutter:
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.2
  page_transition:
  image_picker: ^0.8.2
  place_picker: ^0.9.19-nullsafety
  country_picker: ^2.0.7
  url_launcher: ^6.0.3
  cached_network_image: ^3.1.0
  one_context: ^1.1.1
  persistent_bottom_nav_bar: ^4.0.2
  share_plus: ^3.0.1
  shared_preferences: ^2.0.7
  firebase_auth_mocks: ^0.8.0
  firebase_storage_mocks: ^0.5.0
  google_sign_in_mocks: ^0.2.1
  fake_cloud_firestore: ^1.1.3
  another_flushbar: ^1.10.28
  lottie: ^1.2.1
  flag: ^6.0.0

dev_dependencies:
  mockito:
  build_runner:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  assets:
    - assets/images/
    - assets/lottiefiles/
  uses-material-design: true

