name: hunt_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.4.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.0.3
  firebase_storage: ^10.0.1
  flutter_form_builder: ^6.0.0-nullsafety.1
  flutter_facebook_auth: ^3.5.1
  geolocator: ^7.0.3
  google_maps_flutter: ^2.0.3
  google_sign_in: ^5.0.2
  image_picker: ^0.8.2
  location: ^4.1.1
  place_picker: ^0.9.19-nullsafety
  url_launcher: ^6.0.3
  cached_network_image: ^3.1.0
  country_picker: ^2.0.7
  fluster: ^1.2.0
  one_context: ^1.1.1
  persistent_bottom_nav_bar: ^4.0.2
  share_plus: ^2.1.4

dev_dependencies:
  mockito:
  build_runner:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true

