name: hunt_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.3  
  firebase_auth: ^1.0.2
  cloud_firestore: ^1.0.4
  google_maps_flutter: ^2.0.3
  google_maps_webservice: ^0.0.20-nullsafety.3
  location: ^4.1.1
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.0.1
  geolocator: 7.0.1
  firebase_storage: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
